{% set name = "matplotlive" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotlive-{{ version }}.tar.gz
  sha256: 85acd6c5139d5367093ece736f89bedf82293a7329f6f926e50b80e1ea6e085f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.3.4
    - numpy >=1.15.4

test:
  imports:
    - matplotlive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/matplotlive/
  summary: Stream live plots to a matplotlib figure.
  dev_url: https://github.com/stephane-caron/matplotlive
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
